version: '2'
services:
    mysql:
        image: mysql:latest
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: develop
            MYSQL_USER: test
            MYSQL_PASSWORD: testpassword

    crontab:
        build: ./crontab/
        volumes:
            - ./mysql_backup:/backup_sql
        links:
            - mysql
